# Generated by Django 2.1.2 on 2018-10-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Kurum', 'verbose_name_plural': 'Kurumlar'},
        ),
    ]
