# Generated by Django 2.1.2 on 2018-10-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0002_auto_20181005_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='AddressDetail',
            field=models.CharField(blank=True, max_length=100, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='organization',
            name='City',
            field=models.CharField(blank=True, max_length=100, verbose_name='Şehir/Eyalet'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='organization',
            name='District',
            field=models.CharField(blank=True, max_length=100, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='organization',
            name='eMail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Posta'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='OrgCode',
            field=models.BigIntegerField(blank=True, verbose_name='Kurum Kodu'),
        ),
    ]
