# Generated by Django 2.1.2 on 2018-10-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0004_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='GameRef',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
