# Generated by Django 2.1.2 on 2018-10-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0005_game_gameref'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='GameType',
            field=models.CharField(choices=[('Süper Lig', 'Süper Lig'), ('Türkiye Kupası', 'Türkiye Kupası')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
