# Generated by Django 2.1.2 on 2018-10-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0007_auto_20181005_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='GameRef',
            field=models.CharField(blank=True, max_length=100, verbose_name='Maç Hakemi'),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameType',
            field=models.CharField(choices=[('Türkiye Kupası', 'Türkiye Kupası'), ('Süper Lig', 'Süper Lig')], default=0, max_length=200, verbose_name='Fikstür'),
        ),
    ]
