# Generated by Django 2.1.2 on 2018-10-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0009_auto_20181005_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='GameType',
            field=models.CharField(choices=[('Türkiye Kupası', 'Türkiye Kupası'), ('Süper Lig', 'Süper Lig')], default=0, max_length=200, verbose_name='Fikstür'),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameWeek',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('2', '2'), ('1', '1')], default=0, max_length=200, verbose_name='Hafta'),
        ),
    ]
