# Generated by Django 2.1.2 on 2018-10-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0010_auto_20181005_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='GameWeek',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('1', '1'), ('3', '3')], default=0, max_length=200, verbose_name='Hafta'),
        ),
    ]
