# Generated by Django 2.1.2 on 2018-10-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0011_auto_20181005_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAcreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='GameType',
            field=models.CharField(choices=[('Süper Lig', 'Süper Lig'), ('Türkiye Kupası', 'Türkiye Kupası')], default=0, max_length=200, verbose_name='Fikstür'),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameWeek',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default=0, max_length=200, verbose_name='Hafta'),
        ),
        migrations.AddField(
            model_name='orgacreditation',
            name='AcrGameDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GameDatex', to='Akreditasyon.Game'),
        ),
    ]
