# Generated by Django 2.1.2 on 2018-10-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0012_auto_20181005_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zeynel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zeynel', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orgacreditation',
            options={'verbose_name': 'Misafir', 'verbose_name_plural': 'Misafirler'},
        ),
        migrations.RemoveField(
            model_name='orgacreditation',
            name='id',
        ),
        migrations.AddField(
            model_name='orgacreditation',
            name='AcrGameCode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Akreditasyon.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgacreditation',
            name='AcredidatedGuestIdentity',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Tc Kimlik No'),
        ),
        migrations.AddField(
            model_name='orgacreditation',
            name='AcredidatedGuestName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Misafir Adı'),
        ),
        migrations.AddField(
            model_name='orgacreditation',
            name='AcredidatedLastName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Misafir SoyAdı'),
        ),
        migrations.AddField(
            model_name='orgacreditation',
            name='AcredidatedMobilePhone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameType',
            field=models.CharField(choices=[('Türkiye Kupası', 'Türkiye Kupası'), ('Süper Lig', 'Süper Lig')], default=0, max_length=200, verbose_name='Fikstür'),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameWeek',
            field=models.CharField(choices=[('4', '4'), ('2', '2'), ('3', '3'), ('1', '1')], default=0, max_length=200, verbose_name='Hafta'),
        ),
        migrations.AlterField(
            model_name='orgacreditation',
            name='AcrGameDate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GameDate', to='Akreditasyon.OrgAcreditation'),
        ),
    ]
