# Generated by Django 2.1.2 on 2018-10-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0013_auto_20181005_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zeynel',
        ),
        migrations.AlterField(
            model_name='game',
            name='GameWeek',
            field=models.CharField(choices=[('4', '4'), ('1', '1'), ('3', '3'), ('2', '2')], default=0, max_length=200, verbose_name='Hafta'),
        ),
    ]
