# Generated by Django 2.1.2 on 2018-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akreditasyon', '0015_auto_20181005_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='GameType',
            field=models.CharField(choices=[('Süper Lig', 'Süper Lig'), ('Türkiye Kupası', 'Türkiye Kupası')], default=0, max_length=200, verbose_name='Fikstür'),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameWeek',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('1', '1'), ('4', '4')], default=0, max_length=200, verbose_name='Hafta'),
        ),
    ]
