# Generated by Django 2.1.2 on 2018-10-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repciro',
            name='SalesQTY',
            field=models.FloatField(blank=True, default=0, verbose_name='Satış Miktarı'),
        ),
    ]
