# Generated by Django 2.1.2 on 2018-10-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepServer', '0002_repciro_salesqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='repciro',
            name='SalesTaxBaseAmount',
            field=models.FloatField(blank=True, default=0, verbose_name='VH Satış Tutarı'),
        ),
    ]
