# Generated by Django 2.1.2 on 2018-10-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepServer', '0003_repciro_salestaxbaseamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repciro',
            name='StoreCode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mağaza Kodu'),
        ),
        migrations.AlterField(
            model_name='repciro',
            name='StoreDesc',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mağaza Adı'),
        ),
    ]
