# Generated by Django 2.1.2 on 2018-10-04 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RepServer', '0005_auto_20181005_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repciro',
            name='EndDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='repciro',
            name='SalesInvoiceDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fatura Tarihi'),
        ),
        migrations.AlterField(
            model_name='repciro',
            name='StartDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi'),
        ),
    ]
