# Generated by Django 2.1.2 on 2018-10-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RepServer', '0006_auto_20181005_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repciro',
            name='EndDate',
        ),
        migrations.RemoveField(
            model_name='repciro',
            name='SalesInvoiceDate',
        ),
        migrations.RemoveField(
            model_name='repciro',
            name='StartDate',
        ),
    ]
